// <auto-generated />
using System;
using DmScreenAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DmScreenAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DmScreenAPI.Context.Entities.Cheatsheet", b =>
                {
                    b.Property<int>("Cheatsheetid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Html");

                    b.Property<string>("Name");

                    b.HasKey("Cheatsheetid");

                    b.ToTable("Cheatsheets");
                });

            modelBuilder.Entity("DmScreenAPI.Context.Entities.Creature", b =>
                {
                    b.Property<int>("CreatureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AC");

                    b.Property<int?>("CR");

                    b.Property<int>("Charisma");

                    b.Property<int?>("CharismaBonus");

                    b.Property<string>("Class");

                    b.Property<int>("Constitution");

                    b.Property<int?>("ConstitutionBonus");

                    b.Property<int>("Dexterity");

                    b.Property<int?>("DexterityBonus");

                    b.Property<string>("Image");

                    b.Property<int>("Initiative");

                    b.Property<int?>("InitiativeBonus");

                    b.Property<int?>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int>("PInsight");

                    b.Property<int>("PInvestigation");

                    b.Property<int>("PPerception");

                    b.Property<int?>("ProficiencyBonus");

                    b.Property<string>("Race");

                    b.Property<int>("Speed");

                    b.Property<int>("Strength");

                    b.Property<int?>("StrengthBonus");

                    b.Property<int>("Wisdom");

                    b.Property<int?>("WisdomBonus");

                    b.Property<bool>("isHostile");

                    b.HasKey("CreatureId");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("DmScreenAPI.Context.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Html");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("DmScreenAPI.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DeletedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
